[workspace]
resolver = "2"
members = [
    "projects/branches",
    "projects/guessing_game",
    "projects/hello_cargo",
    "projects/loops",
    "projects/ownership",
    "projects/structs",
    "projects/modules",
    "projects/collections",
    "projects/concurrency",
]